#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SXA.Theme.Optimizations
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 10 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Microsoft.Extensions.DependencyInjection;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.DependencyInjection;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.Grid.Extensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.MarkupDecorator.Extensions;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.SitecoreExtensions.Extensions;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.Theming.Bundler;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.Theming.Configuration;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.Theming.Models;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using Sitecore.XA.Foundation.Theming.Services;
    
    #line default
    #line hidden
    
    #line 13 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using SXA.Theme.Optimizations.Enums;
    
    #line default
    #line hidden
    
    #line 12 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    using SXA.Theme.Optimizations.Services;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SxaLayout/Optimized SxaLayout.cshtml")]
    public partial class Optimized_SxaLayout : System.Web.Mvc.WebViewPage<Sitecore.Mvc.Presentation.RenderingModel>
    {
        public Optimized_SxaLayout()
        {
        }
        public override void Execute()
        {















            
            #line 15 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
  
    var assetConfiguration = AssetConfigurationReader.Read();
    var assetLinks = AssetLinksGenerator.GenerateLinks(new ThemesProvider());
    var includes = ServiceLocator.ServiceProvider.GetService<IHTMLIncludesService>().GetHTMLIncludes();

    var themeOptimizationSettings = CachingService.GetThemeOptimizationsSettings();
    var scriptsRenderAttribute = themeOptimizationSettings.RenderScriptsAs == ScriptAttributes.Async ? "async" : themeOptimizationSettings.RenderScriptsAs == ScriptAttributes.Defer ? "defer" : string.Empty;


            
            #line default
            #line hidden
WriteLiteral(@"
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class=""no-js lt-ie9 lt-ie8 lt-ie7""> <![endif]-->
<!--[if IE 7]>         <html class=""no-js lt-ie9 lt-ie8""> <![endif]-->
<!--[if IE 8]>         <html class=""no-js lt-ie9""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class=""no-js"" lang=""");


            
            #line 29 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                     Write(Model.Item.Language.Name);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n<!--<![endif]-->\r\n<head>\r\n");


            
            #line 32 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
     if (!assetConfiguration.RequestAssetsOptimizationDisabled && !Sitecore.Context.PageMode.IsExperienceEditor && themeOptimizationSettings.ScriptsLocation == ScriptLocations.Top)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script ");


            
            #line 34 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
           Write(scriptsRenderAttribute);

            
            #line default
            #line hidden
WriteLiteral(" src=\"");


            
            #line 34 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                                        Write(themeOptimizationSettings.ScriptUrl);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


            
            #line 35 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 37 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
     foreach (string style in assetLinks.Styles)
    {
        if (themeOptimizationSettings.DeferCss)
        {
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
       Write(Html.Raw(style.Replace("rel=\"stylesheet\"", "rel=\"preload\" as=\"style\"")));

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                                                                                          
        }

        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
   Write(Html.Raw(style));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                        
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 47 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
     foreach (var include in includes.Head)
    {
        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
   Write(Html.Raw(include.HTML));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 52 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
Write(Html.Sxa().VisitorIdentification());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 53 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
Write(Html.Sxa().Placeholder("head"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");


            
            #line 55 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
 Write(Html.Sxa().Body().Decorate());

            
            #line default
            #line hidden
WriteLiteral(">\r\n    ");


            
            #line 56 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
Write(Html.Sitecore().Placeholder("body-top"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 58 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
     foreach (var include in includes.BodyTop)
    {
        
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
   Write(Html.Raw(include.HTML));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 63 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
Write(Html.Sxa().GridBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");


            
            #line 65 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
Write(Html.Sitecore().Placeholder("body-bottom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 67 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
     foreach (var include in includes.BodyBottom)
    {
        
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
   Write(Html.Raw(include.HTML));

            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 72 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
     if (assetConfiguration.RequestAssetsOptimizationDisabled || Sitecore.Context.PageMode.IsExperienceEditor)
    {
        foreach (string include in assetLinks.Scripts)
        {
            
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
       Write(Html.Raw(include));

            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                              
        }
    }
    else if (themeOptimizationSettings.ScriptsLocation == ScriptLocations.Bottom)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script ");


            
            #line 81 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
           Write(scriptsRenderAttribute);

            
            #line default
            #line hidden
WriteLiteral(" src=\"");


            
            #line 81 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
                                        Write(themeOptimizationSettings.ScriptUrl);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


            
            #line 82 "..\..\Views\SxaLayout\Optimized SxaLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!-- /#wrapper -->\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
