name: CI Build
on:
  push:
    branches: [ "main", v* ]
  pull_request:
    branches: [ "main", v* ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x

    - name: Restore Sitecore.CLI dotnet tool
      run: dotnet tool restore

    - name: Restore Sitecore.CLI packages and files
      run: dotnet sitecore init

    - name: Generate Core database items file
      run: dotnet sitecore itemres create -i SXA.Theme.Optimizations.Core --output SXA.Theme.Optimizations\App_Data\items\core\sxa.theme.optimizations --overwrite

    - name: Generate Master database items file
      run: dotnet sitecore itemres create -i SXA.Theme.Optimizations.Master --output SXA.Theme.Optimizations\App_Data\items\master\sxa.theme.optimizations --overwrite

    - name: Build Solution
      run: dotnet build SXA.Theme.Optimizations/SXA.Theme.Optimizations.csproj -c Release

    - name: Pack Nuget Package
      run: dotnet pack SXA.Theme.Optimizations/SXA.Theme.Optimizations.csproj -c Release